import os
import sys
from app import create_app
from scripts.extensions import db
from scripts.models import Challenge, Category
from scripts.import_export import import_challenges_from_yaml
from scripts.config import TestConfig # Import TestConfig
import yaml

# Add Prism directory to PYTHONPATH if not already there, for Prism models
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'Prism', 'prism')))


def verify_import():
    # Set up the app with a test configuration
    app = create_app(TestConfig) # Pass the TestConfig object

    with app.app_context():
        # Ensure a clean slate for testing
        db.drop_all()
        db.create_all()

        print("--- Testing 'Coding Challenge: Python Sum' import ---")
        # Path to the import.yaml generated by Prism for the coding challenge
        coding_challenge_yaml_path = os.path.join(
            os.path.dirname(__file__), '..', 'Prism', 'tests', 'yaml_test_challenge', 'import.yaml'
        )

        print(f"Importing challenges from: {coding_challenge_yaml_path}")
        import_challenges_from_yaml(app, coding_challenge_yaml_path)

        # Verify the challenge was imported correctly
        challenge = Challenge.query.filter_by(name="Coding Challenge: Python Sum").first()

        assert challenge is not None, "Coding Challenge: Python Sum was not imported."
        print("Challenge 'Coding Challenge: Python Sum' found in DB.")

        assert challenge.points == 100
        assert challenge.category.name == "Programming"
        assert challenge.challenge_type == "CODING"
        assert challenge.language == "python3"
        assert "def solve():" in challenge.starter_code
        assert challenge.test_cases, "No test cases were imported for the coding challenge."
        assert len(challenge.test_cases) > 0, "Test cases list is empty."
        first_test_case = challenge.test_cases[0]
        assert first_test_case.expected_output == "30"
        assert first_test_case.input_data == "10\n20"
        assert challenge.setup_code == ""
        assert challenge.multi_flag_type == "SINGLE"
        assert len(challenge.flags) == 0

        print("All assertions for 'Coding Challenge: Python Sum' passed!")
        print("--- Import verification complete ---")

if __name__ == '__main__':
    verify_import()
